#cloud-config
# update apt on boot
apt_upgrade: true
# install nginx
packages:
- nginx
write_files:
- content: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>StackPath - Amazon Web Services Instance</title>
      <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
      <style>
        html, body {
          background: #000;
          height: 100%;
          width: 100%;
          padding: 0;
          margin: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          flex-flow: column;
        }
        img { width: 250px; }
        svg { padding: 0 40px; }
        p {
          color: #fff;
          font-family: 'Courier New', Courier, monospace;
          text-align: center;
          padding: 10px 30px;
        }
      </style>
    </head>
    <body>
      <img src="https://burtonavenue.com/wp-content/uploads/2018/03/hello_pillow-400x400.jpg">
      <p> -------- </strong></p>
      <p>       From : Rohit Tiwari</strong></p>
    </body>
    </html>
  path: /usr/share/app/index.html
  permissions: '0644'
runcmd:
- cp /usr/share/app/index.html /var/www/html/index.html

# Mount /dev/xvdf to /var/log
fs_setup:
 - cmd: mkfs -t %(filesystem)s -L %(label)s %(device)s
   label: logs
   filesystem: 'ext4'
   overwrite: false
   device: '/dev/xvdf'
mounts:
 - [ /dev/xvdf, /var/log, "ext4", "defaults,nofail", "0", "2" ]
